# Generated by Django 4.2.4 on 2023-10-16 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('difficulty_level', models.CharField(max_length=20, verbose_name='Difficulty Level')),
                ('duration_minutes', models.PositiveIntegerField(verbose_name='Duration Minutes')),
                ('equipment', models.CharField(max_length=90)),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='Video URL')),
                ('calories_burned', models.PositiveIntegerField(default=0, verbose_name='Calories Burned')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='Is Favourite')),
            ],
        ),
    ]
