# Generated by Django 4.2.4 on 2023-10-17 12:29

from django.db import migrations


def set_rarity(apps, schema_editor):
    item = apps.get_model('main_app', 'Item')

    for current_item in item.objects.all():
        if current_item.price <= 10:
            current_item.rarity = "Rare"
        elif 11 <= current_item.price <= 20:
            current_item.rarity = "Very Rare"
        elif 21 <= current_item.price <= 30:
            current_item.rarity = "Extremely Rare"
        else:
            current_item.rarity = "Mega Rare"
        current_item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_item'),
    ]

    operations = [
        migrations.RunPython(set_rarity)
    ]
