# Generated by Django 4.2.4 on 2023-10-17 12:35

from django.db import migrations


def set_price_and_category(apps, schema_editor):
    smartphone = apps.get_model('main_app', 'Smartphone')

    for current_smartphone in smartphone.objects.all():
        current_smartphone.price = len(current_smartphone.brand) * 120

        if current_smartphone.price >= 750:
            current_smartphone.category = "Expensive"
        else:
            current_smartphone.category = "Cheap"

        current_smartphone.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_smartphone'),
    ]

    operations = [
        migrations.RunPython(set_price_and_category)
    ]
