# Generated by Django 4.2.4 on 2023-10-17 12:47

from django.db import migrations
from django.utils import timezone


def modify_delivery_and_warranty(apps, schema_editor):
    order = apps.get_model('main_app', 'Order')

    for current_order in order.objects.all():
        if current_order.status == "Pending":
            current_order.delivery = current_order.order_date + timezone.timedelta(days=3)
        elif current_order.status == "Completed":
            current_order.warranty = "24 months"
        elif current_order.status == "Cancelled":
            current_order.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_order'),
    ]

    operations = [
        migrations.RunPython(modify_delivery_and_warranty)
    ]
